spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://root:r00t@localhost:27017
      database: retro
axon:
  axonserver:
    enabled: false
  serializer:
    events: jackson
  kafka:
    bootstrap-servers: localhost:9092
    client-id: retro-api
    default-topic: retro_events
    properties:
      security.protocol: PLAINTEXT

    publisher:
      confirmation-mode: transactional

    producer:
      transaction-id-prefix: kafka-sample
      retries: 0
      event-processor-mode: subscribing
      # For additional unnamed properties, add them to the `properties` map like so
      #properties:
      #  some-key: [some-value]

    fetcher:
      poll-timeout: 3000

    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      event-processor-mode: tracking
      # For additional unnamed properties, add them to the `properties` map like so
      #properties:
      #  some-key: [some-value]
